config/routes.rb
Rails.application.routes.draw do
  resources :hotels do
    post :scrape, to: 'hotels#scrape', on: :collection
  end

  root to: 'hotels#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
end

app/models/hotels_spider.rb
class HotelsSpider < Kimurai::Base
  @name = 'hotels_spider'
  @engine = :mechanize

  def self.process(url)
    @start_urls = [url]
    self.crawl!
  end

  def parse(response, url:, data: {})
    response.xpath("//div[@class='card hotel-card']").each do |hotel|
      item = {}

      item[:name] = hotel.css('span.hotel-name').text
      item[:reviews_score] = hotel.css('div.button-reviews span')[1].text.split('/')[0].to_f
      item[:actual_rate] = hotel.css('span.current_rate').text.tr('$.', '').squish.to_i
      item[:last_rate] = hotel.css('span.last_rate').text.tr('$.', '').squish.to_i
      item[:city_name] = response.css('h1.city-title').text.squish.gsub('HOTELES EN ', '').parameterize

      Hotel.where(item).first_or_create
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def scrape
    url = 'https://ayendarooms.com/hoteles/medellin'
    response = HotelsSpider.process(url)

    if response[:status] == :completed && response[:error].nil?
      flash[:notice] = 'Successfully scraped url'
    else
      flash[:alert] = response[:error]
    end
  rescue StandardError => e
    flash[:alert] = "Error: #{e}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:name, :reviews_score, :actual_rate, :city_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_with(model: hotel, local: true) do |form| %>
  <% if hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
        <% hotel.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :reviews_score %>
    <%= form.number_field :reviews_score %>
  </div>

  <div class="field">
    <%= form.label :actual_rate %>
    <%= form.text_field :actual_rate %>
  </div>

  <div class="field">
    <%= form.label :city_name %>
    <%= form.text_field :city_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hotels</h1>

<%= button_to 'Scrape', scrape_hotels_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Reviews score</th>
      <th>Actual rate</th>
      <th>Last rate</th>
      <th>City name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.name %></td>
        <td><%= hotel.reviews_score %></td>
        <td><%= hotel.actual_rate %></td>
        <td><%= hotel.last_rate %></td>
        <td><%= hotel.city_name %></td>
        <td><%= link_to 'Show', hotel %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
        <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel', new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/scrape.html.erb
<p id="notice"> <%= notice %> </p>
<p id="alert"> <%= alert %> </p>

<%= link_to 'Go back', root_path %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>

<p>
  <strong>Reviews score:</strong>
  <%= @hotel.reviews_score %>
</p>

<p>
  <strong>Actual rate:</strong>
  <%= @hotel.actual_rate %>
</p>

<p>
  <strong>City name:</strong>
  <%= @hotel.city_name %>
</p>

<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebScraper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>